version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Admin@srout2#
      MYSQL_DATABASE: country_db
    ports:
      - "3307:3306"

